### ISSUE TITLE
Left click menu cause left click in game.

### ISSUE THREAD

**Issue by cnMolean** [PyvesB/AdvancedAchievements#783] opened 2020-07-09 02:13 UTC
:information_source: **Basic information**

* Advanced Achievements version: 6.1.3
* Minecraft version: 1.16.1
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: yes

:beetle: **Description**

Type `/aach list` then click achievement catagory, player will waving fist or use item in hand.

:page_facing_up: **Server logs**

No error log.

:wrench: **Configuration**

Just use default config.

**Comment by PyvesB** [comment] 2020-07-09 17:17
Hello @cnMolean,

I am able to reproduce this issue. I don't think it's a huge problem per say, but I'll try to look into it in the coming weeks. Anyone else reading this issue, feel free to have a look as well! :wink:

**Comment by cnMolean** [comment] 2020-07-12 01:59
I test 1.8 1.12 and 1.15. They worked perfect. Only 1.16+ have this problem. 

This bug breaks GUI if bind some left click action to item.

**Comment by PyvesB** [comment] 2020-07-18 16:59
I rebuilt the very latest version of Spigot and did some more digging. This doesn't seem to be an issue caused by Advanced Achievements. After all, the _/aach list_ inventory handling code hasn't changed much in recent years and still works fine on all Minecraft versions from 1.7.9 to 1.15.2. I'm also able to reproduce the issue with very simple code samples that don't involve the full GUI.

I've reported a bug on the [Spigot issue tracker](https://hub.spigotmc.org/jira/browse/SPIGOT-6008). Please upvote the bug and add any new information you may have, if any.

**Comment by PyvesB** [comment] 2020-07-20 07:16
Unfortunately, the Spigot team have said that it's "a client thing and not caused by or fixable by Spigot". There doesn't seem to be any way prevent the arm swinging in Advanced Achievements or in Spigot itself.

The only way forward would be to hope that it gets fixed in Minecraft itself. If you feel strongly about this, please report a bug on the [Minecraft issue tracker](https://minecraft.net/en-us/bugs/pc/).

**Closed** 2020-07-29 17:42 UTC
Labels: bug, not-aach
