### ISSUE TITLE
Disabling achievements for no reason

### ISSUE THREAD

**Issue by danyaelgaina** [PyvesB/AdvancedAchievements#735] opened 2020-05-13 16:57 UTC
https://telegra.ph/YYep-05-13 link of config
Upon being enable targetsshot is being removed and
This shows in console
[AdvancedAchievements] Loaded 23 achievements in 7 categories.
>.... [16:54:50 INFO]: [AdvancedAchievements] 44 disabled categories: [DistanceFoot, ItemBreaks, Custom, DistanceHorse, Beds, TargetsShot, Brewing, Trades, Breaks, AdvancementsCompleted, Enchantments, DistanceBoat, ConsumedPotions, Crafts, MaxLevel, HoePlowings, RaidsWon, Fertilising, PlayerCommands, Taming, WaterBuckets, EnderPearls, Milk, Riptides, DistancePig, Shear, EatenItems, Places, AnvilsUsed, DistanceMinecart, MusicDiscs, Commands, Fireworks, Smelting, DistanceLlama, Breeding, PetMasterReceive, PetMasterGive, DistanceGliding, LavaBuckets, Snowballs, Eggs, Fish, Treasures]
After this targetsshot is auto remove from config

**Comment by PyvesB** [comment] 2020-05-13 17:39
Hello @danyaelgaina,

The `TargetsShot` category is empty in your configuration:
````
TargetsShot: {}
````

Therefore, it is being disabled. 😉

**Comment by danyaelgaina** [comment] 2020-05-14 01:40
Then how do i fix this
+ I also want to enable enderpearls but it just wont
 I tried putting player there and aach add achname PLAYER 1

**Comment by PyvesB** [comment] 2020-05-14 06:57
Well, simply add achievements to the category so that it isn't empty!

**Comment by danyaelgaina** [comment] 2020-05-14 06:58
There are TargetsShot achievements in the config tho

**Comment by PyvesB** [comment] 2020-05-14 17:09
Well, you've duplicated the category in the configuration, the plugin is picking up the empty one and therefore disabling the category.

**Comment by PyvesB** [comment] 2020-05-23 10:46
Assuming the problem is fixed, closing!

**Closed by PyvesB** 2020-05-23 10:46 UTC
Labels: general support
