### ISSUE TITLE
Money using Vault

### ISSUE THREAD

**Issue by kilionline** [PyvesB/AdvancedAchievements#695] opened 2020-03-29 21:49 UTC
The money reward system with Vault doesnt work for me. I use an eco plugin which has worked with vault before. If i add a money reward to an achievement no error comes up but the money isnt added to the account either. pls help :)

**Comment by PyvesB** [comment] 2020-03-30 18:32
Hello @kilionline, I cannot reproduce any issues with money rewards. See #618 for more information. 😉

**Comment by The4Shadowmask** [comment] 2020-04-04 07:44
I've also been having issues with the money reward system for the achievements. I went through and edited the config.yml file and gave different achievements money rewards. It wasn't working so I just ignored it for the most part, but I just happened to be scrolling through the console and found that it recognized I inputted a money reward but had an issue connecting to Vault. I was wondering if there was anything that had to be done to connect the two. Thanks! 

![Vault Error](https://user-images.githubusercontent.com/63142197/78421507-3fd54e00-7626-11ea-9561-56653cb6f1f6.PNG)

**Comment by PyvesB** [comment] 2020-04-04 10:57
See my message above.

**Comment by kilionline** [comment] 2020-04-04 10:58
Unfortunatly, i couldn't find any solution and just ended up deinstalling the Plugin. If you find anything, please let me notice. Thanks

**Comment by PyvesB** [comment] 2020-05-02 06:22
Closing. None of the four people involved in this issue or the linked issue have been willing to help with the investigation. No steps to reproduce have been provided. Basic information such as Vault and Advanced Achievements versions are to date still missing.

If you want to see this resolved:
* either demonstrate that this is a problem with Advanced Achievements and submit a pull request to fix the issue.
* provide comprehensive information with all the steps necessary to reliably reproduce the issue.

**Closed by PyvesB** 2020-05-02 06:22 UTC
Labels: cannot reproduce
