### ISSUE TITLE
Big lags due to Advanced Achievements

### ISSUE THREAD

**Issue by MaxIsV** [PyvesB/AdvancedAchievements#709] opened 2020-04-16 10:51 UTC
Hello. Today the server freezes for some time, timings showed that huge lags created the Advanced Achievements plugin
![AACH-lags](https://user-images.githubusercontent.com/58142896/79447937-49c55c80-7fe9-11ea-9a9b-9939acf0ca62.png)
Timings: https://timings.aikar.co/?id=476fed810ac44f3ebb75d7a118da4613

**Comment by PyvesB** [comment] 2020-04-19 15:06
Hello @MaxIsV, that's odd, it looks like Advanced Achievements consumed almost 50s of server processing time over a two minute period, whereas it had only consumed half a second over the previous ten minutes. That's a 500% drop in performance.

Does this happen on a regular basis or was it a one-time problem? Was anything in particular happening on your server at that time? I can't see any new player connections or anything else that looks unusual.

**Comment by MaxIsV** [comment] 2020-04-20 20:12
Hello. It was one-time, because I no longer observed such jumps from aach. I do not know what was happening on the server then, but I saw a low TPS from the console and do a timings report.

**Comment by PyvesB** [comment] 2020-04-21 17:16
Out of interest, what database type do you use?

Was there anything in the server's logs around that time?

**Comment by MaxIsV** [comment] 2020-04-22 10:35
I am using MySQL.

I opened the server logs and really found errors there: https://pastebin.com/E1ufRBxS

The time of these errors clearly coincides with the lags.

**Comment by PyvesB** [comment] 2020-04-22 17:18
I'm surprised the stack traces all show `org.sqlite.jdbc` if you're using MySQL. Unless I'm missing something, I would expect `com.mysql.jdbc` instead. Could you double check that there's no database file in use in the _plugins/AdvancedAchievements_ folder?

**Comment by MaxIsV** [comment] 2020-04-22 18:21
Oh yeah. I do not have a database connected for AACH

**Comment by PyvesB** [comment] 2020-04-23 07:35
There are quite a few reports of this occasionally happening with other plugins, on the Spigot forum and various other places.

As Advanced Achievements heavily relies on its database for a huge amount of player statistics, a temporary drop in disk performance would basically lock all SQLite operations. This happened a couple of times back when I owned a server, with Dynmap and Factions taking down the server because the SSD stopped responding for ~30 seconds.

Another explanation could be a bug with the SQLite drivers, which Spigot manages directly unlike H2 and PostgreSQL ones. Given that you're running Minecraft 1.12, they would be  at least three years old, if not more.

There still is a possibility that there's a bug in the way Advanced Achievements is making the SQL queries, but given that there aren't any other reports for this plugin, it's unlikely. I would need a way of reproducing this to be able to investigate.

Given that this was a one-off and it's unlikely that we'll reach a conclusion with the data we've got, I suggest we close this. We can always reopen if anything new comes to light. :wink:

**Closed** 2020-04-23 19:44 UTC
Labels: investigate
