### ISSUE TITLE
Continued lag by Advanced Achievements

### ISSUE THREAD

**Issue by masterolos09** [PyvesB/AdvancedAchievements#267] opened 2017-12-02 18:10 UTC
There are 50 people playing on my server, when the AdvancedAchievements plugin is uploaded, there are TPS drops and there are lags, and how to remove AdvancedAchievements TPS is fixed 19.99 and there are no lags at the same number of players

Advanced Achievements 5.3.3
Linux Debian-91-stretch-64-minimal 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64
PHPMyAdmin is also the latest
Java 8 is also the latest
PaperSpigot 1.12.2 latest

The entire system and database is well configured, I have 52 plugins on the server, but when I install Advanced Achievements, lags are right away.

**Comment by PyvesB** [comment] 2017-12-02 18:34
Closing as duplicate of #260. Keeping on stating that everything is perfect on your side even though it apparently isn't and refusing to try out some of the recommendations or alternatives I have previously suggested is not constructive. You have repeatedly lacked basic good manners in all your messages so far (not a single "Hello", "Please", "Thanks", etc.), therefore I will stop wasting my time and providing support for someone so ill-mannered and unappreciative.

**Closed by PyvesB** 2017-12-02 18:34 UTC
Labels: duplicate, invalid
