### ISSUE TITLE
Progression not shown

### ISSUE THREAD

**Issue by PapiCapi** [PyvesB/AdvancedAchievements#806] opened 2020-08-01 12:24 UTC
:information_source: **Basic information**
I just updated to the new version of AdvancedAchievements and now, the progression bar is empty ( http://prntscr.com/ts9e41 instead of http://prntscr.com/ts9e8f ).
However there is only 1 achievement where this bar is shown so this issue does not affect all of them.

The isn't any error in the logs when opening /aach list.

* Advanced Achievements version: 
6.1.3
* Minecraft version: 
Spigot 1.16.1
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: 
yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: 
yes

:question: **Help request**

How can i re enable the progression in most of the achievements ?
:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment] 2020-08-01 12:46
Hello @PapiCapi,

This is a duplicate of #791, therefore closing.

**Closed by PyvesB** 2020-08-01 12:46 UTC
Labels: duplicate
