### ISSUE TITLE
ConsumedPotions Issue

### ISSUE THREAD

**Issue by Oicurdead** [PyvesB/AdvancedAchievements#571] opened 2019-08-27 03:21 UTC
Hello, I am having some issues in regards to certain potions not triggering the ConsumedPotions achievement. The only potions that trigger it are: Mundane, Thick, Awkward, Turtle Master, Healing, and Harming. I saw in a previous issue you said this plugin doesn't support Paper, which I use but that was almost two years ago and hopefully something may have changed. I'm using the latest version of this plugin and running Paper-174.

**Comment by PyvesB** [comment] 2019-08-28 18:00
Hello @Oicurdead,

Could you give me an example of potion that is _not_ working? Also, what Minecraft version does Paper-174 correspond to?

Cheers,

Pyves

**Comment by Oicurdead** [comment] 2019-08-28 23:25
So the server is currently running 1.14.4. The potions not triggering the achievement are: Night Vision, Invisibility, Leaping, Fire Resistance, Swiftness, Slowness, Water Breathing, Poison, Regen, Strength, Weakness, Luck, and Slowfalling. I went through and tested each after I was alerted to the issue.

**Comment by PyvesB** [comment] 2019-08-31 20:54
I am not able to reproduce this issue, both night vision and strength were successfully counted. Could you please try on a server with no other plugins, there may be some sort of conflict.

**Comment by Oicurdead** [comment] 2019-09-01 01:54
Looks like it may be a conflict issue, I put the plugin on our test server which doesn't have as much plugins and it seems to work fine. Are there any known conflicts with popular plugins? Here is our plugin list, https://gyazo.com/fb3543935c63166ceceae4006e43b3ca

**Comment by PyvesB** [comment] 2019-09-01 07:54
I don't know any plugins that could cause issues with potions. I suggest removing the other plugins little by little (using a binary search approach) when there aren't too many players logged in, and you'll soon know what the culprit is!

**Comment by Oicurdead** [comment] 2019-09-01 17:10
It seems our conflict is with OldCombatMechanics, I moved the Jar we had on our live server to the test server and it seems the same potions listed above work/dont work. I don't know if there is a fix for this (other than removing the plugin), if not I can probably rework the achievement so the players know only a handful of potions will trigger it.

**Comment by PyvesB** [comment] 2019-09-01 17:21
Is it this [plugin](https://www.spigotmc.org/resources/oldcombatmechanics-disable-1-9-hit-cooldown.19510/)?

**Comment by Oicurdead** [comment] 2019-09-01 17:26
That is the one.

**Comment by PyvesB** [comment] 2019-09-01 18:37
Here you go, the potions you claim are working can all be found in OldCombatMechanics's source code [here](https://github.com/gvlfm78/BukkitOldCombatMechanics/blob/64f175446fe03cb8fd96bf07827111db0af92bf4/src/main/java/gvlfm78/plugin/OldCombatMechanics/module/ModuleOldPotionEffects.java#L39). All others are disabled and will be ignored by other plugins, such as Advanced Achievements. You can maybe disable the OldPotionEffects module in OldCombatMechanics's configuration or add all new potions to the `old-potion-effects` parameter. 😉

**Comment by Oicurdead** [comment] 2019-09-01 19:09
Great, thank you for the help!

**Comment by PyvesB** [comment] 2019-09-01 20:26
> 
> 
> Great, thank you for the help!

You're welcome! I'll close this issue as we've gotten to the bottom of the problem. Feel free to add a star to the repository!

**Closed by PyvesB** 2019-09-01 20:26 UTC
Labels: general support
