### ISSUE TITLE
Create your own categories/advancement paths.

### ISSUE THREAD

**Issue by IgnisCraft** [PyvesB/AdvancedAchievements#745] opened 2020-06-01 19:23 UTC
Hi there, I absolutely love the plugin and can't wait to support it as my server grows. I just have one specific request that I'd love to see added and I'm sure I'm not the only one who would use this feature. I have multiple types of "break quests" that I want to have on a track so to speak, so like mine 100 stone, then 500 stone, then 1,000 stone etc. and I also have one that is for chopping logs, but I don't want them to be stuck in the same GUI under breaks. I would like to divide them as Stone Mined and Logs Chopped, so I would suggest allowing us to create our own category in the GUIs. just allowing us to name it then add Breaks, Enchant, etc. it would allow us to create achievement paths. It could be pretty versatile too, like making a player have to enchant a pickaxe AND break x amount of blocks after you're a few advancements in. Thank you very much, hopefully the suggestion is good and I'm sure plenty of people would love this feature.

**Comment by PyvesB** [comment] 2020-06-06 08:45
Hello @IgnisCraft ,

The first part of your message about GUI layout seems to be a duplicate of #593. The second part about achievements conditions that span multiple categories seems related to #82.

**Closed** 2020-06-13 09:54 UTC
Labels: duplicate
