### ISSUE TITLE
1.7.10 bug

### ISSUE THREAD

**Issue by Xiazihong** [PyvesB/AdvancedAchievements#404] opened 2018-07-28 10:27 UTC
`[18:23:17] [Server thread/INFO]: [AdvancedAchievements] Enabling AdvancedAchievements v5.9.0
[18:23:17] [Server thread/ERROR]: Error occurred while enabling AdvancedAchievements v5.9.0 (Is it up to date?)
java.lang.NoSuchMethodError: com.hm.achievement.DaggerAdvancedAchievementsComponent$Builder.<init>(Lcom/hm/achievement/DaggerAdvancedAchievementsComponent$Builder;)V
	at com.hm.achievement.DaggerAdvancedAchievementsComponent.builder(DaggerAdvancedAchievementsComponent.java:340) ~[?:?]
	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:43) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:359) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:420) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:352) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:507) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:481) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:441) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:353) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`

**Comment by PyvesB** [comment] 2018-07-28 11:54
Closing as duplicate of #402 . 😉

**Closed by PyvesB** 2018-07-28 11:54 UTC
