### ISSUE TITLE
Multi-line Message:

### ISSUE THREAD

**Issue by XenXn** [PyvesB/AdvancedAchievements#195] opened 2017-05-23 21:28 UTC
Hello,

First, thank you for a great plugin!

I'm sure this is more of a formatting question than about your plugin, but my eyes are going crossed from configuring plugins, reading documentation, and scrolling through console lines haha.. i'm trying to make a 2nd line in the _Message:_ field.  I can't seem to find the proper way.  I did try this below, as i've seen it used in another plugin recently:

```
  ogtester:
    Name: ogtester
    DisplayName: OG Tester
    Goal: Be a pre-release tester
    Message: You are the finest of the fine...\nYou are an OG Tester!

```

Thanks in advance for your time.

**Comment by PyvesB** [comment] 2017-05-23 22:13
Hello,

Not sure whether it's possible, it may simply not be supported in item lores for instance. I will look into it though! ;-)

Cheers,

Pyves

**Comment by XenXn** [comment] 2017-05-24 00:02
Much appreciated.  I have left you a tip for your time.  Cheers!

**Comment by PyvesB** [comment] 2017-05-24 18:37
I've done some testing. If you put double quotes around the _Message_, the break line will properly happen in the chat when receiving the achievements, and in the books. Unfortunately this doesn't seem to work in /aach list and in the title that appears in the middle of the screen.

I can nevertheless perform the line breaking in a more "manual" way, by adding some extra code in the plugin to handle "\n" in /aach list as well. As an alternative, I could also make /aach list automatically break lines when it thinks that the _Message_ is too long. Probably the best way to go, as it avoids users making any changes and having to add "\n" in the config. Can you confirm that it was in /aach list that the line length was annoying you the most, or am I off track here?

As far as the title appearing in the middle of the screen is concerned, I don't think I can do anything to break lines.

Thanks for the tip, very much appreciated! If you provide me with a link to your server, I can add it to the plugin's page on Bukkit and Spigot. ;-)

**Comment by XenXn** [comment] 2017-05-24 22:45
Hello,

Thanks for looking into this.  I actually got ahead of myself and forgot that the _Message_ line was used for more than just the title text that pops-up in the middle of the screen.  That is really what I was looking to accomplish was to break the lines when that big text popped up after earning the achievement.  

After messing with it a bit more and seeing how it appears in books, it would probably make more sense to just change the way I planned on styling the _Message_ line and using the plugin as it is now.

I didn't even realize that /aach list used the _Message_ line but after playing with it, it seems that both completed and achievements in progress will use the _Goal_ line instead of _Message_ in the /aach list which works perfect for me.

I truly appreciate your time looking into this for me.  My server isn't quite open yet but once i'm ready to launch i'll gladly donate to your project again for a spot on your listing page.  I feel this plugin is worth being premium, so it will not bother me at all to contribute a little more to it.  Thanks again for your time.

**Comment by PyvesB** [comment] 2017-05-25 17:37
> it seems that both completed and achievements in progress will use the Goal line instead of Message in the /aach list

That's not intended behaviour, there's a small bug in the code, fixed by bc4b873ef693fcf26808040bc3294194de910fa9. Thanks for spotting it!

I didn't realise you wanted to do the splitting in the title. Unfortunately, as said in the previous message, I don't think I can do anything about it. Nevertheless, if ever you do find a plugin that splits the title, I would be curious to see how they do it. In the end, if you'll change the _Messages_ on your side, everything is fine I guess.

Please feel free to open new issues if you have any other questions or concerns!

**Closed by PyvesB** 2017-05-25 17:37 UTC
Labels: help wanted/question, investigate

**Comment by XenXn** [comment] 2017-05-25 18:57
I'm new to Github so forgive me if it's not proper etiquette to reply to a closed issue.  Just wanted to let you know I did find a plugin that can split titles.

https://www.spigotmc.org/resources/titlemanager.1049/

**Comment by PyvesB** [comment] 2017-05-25 19:25
Are you sure about this? I gave it a quick try, but I could not break lines properly. You have one line for the title (used by the _DisplayName_ in Advanced Achievements), and one line for the subtitle (_Message_ in Advanced Achievements), but I was not able to split the sub-title line into two lines for instance.

**Comment by XenXn** [comment] 2017-05-26 00:31
Hmm ok I didn't actually try it myself, I just saw this in the sample config and assumed it was breaking lines in the title:
``` 
 announcements:
    my-announcement:
      interval: 60
      timings:
        fade-in: 20
        stay: 40
        fade-out: 20
      titles:
      - '&aThis is the 1st title announcement\n&aThis is the subtitle'
      - '&bThis is the 2nd title announcement\n&bThis is the subtitle'

```

**Comment by PyvesB** [comment] 2017-05-26 06:55
No, that just separates title and subtitles. ;-)
