### ISSUE TITLE
Support if MythicMobs

### ISSUE THREAD

**Issue by Jokki157** [PyvesB/AdvancedAchievements#343] opened 2018-04-21 22:23 UTC
Hey, is it possible to add support for mythicmobs? I have a rpg server under progress and it would be cool to add achevements for the different bosses that i have. Is this possible for you tp add? :D

**Comment by supertassu** [comment] 2018-04-22 05:04
Duplicate of #301

**Closed** 2018-04-22 07:35 UTC
Labels: duplicate
