### ISSUE TITLE
Issue with placeholders place/break

### ISSUE THREAD

**Issue by PoulpinSky** [PyvesB/AdvancedAchievements#669] opened 2020-02-22 16:35 UTC
While i try to use placeholders %aach_breaks_stone% or %aach_places_dirt%, it return me the placeholders, not a number
![2020-02-22_17 31 59](https://user-images.githubusercontent.com/52743366/75095864-9b2d0e80-5599-11ea-8c8e-48d38e10f176.png)

Same issue than issue #615.

Please, fix it !

**Comment by PyvesB** [comment] 2020-02-23 12:03
> Same issue than issue #615.

Same answer as in #615. Cannot reproduce. If you want any chance of getting this fixed:
* please provide basic information about your server setup.
* please share your configuration. This was requested both in #615 and the [contribution guidelines](https://github.com/PyvesB/AdvancedAchievements/blob/master/CONTRIBUTING.md).
* please provide detailed steps on how to easily reproduce. PlaceholderAPI support was contributed by another developer, I know pretty much nothing about the plugin and don't have it installed.

**Comment by PoulpinSky** [comment] 2020-02-23 17:34
Serveur : paper 1.12
Aach : lastest version
Placeholderapi : Laster version

Config : https://pastebin.com/y1Wk83Ys

**Comment by PoulpinSky** [comment] 2020-02-23 17:35
And i show the placeholders with hologram from CMI and menu from deluxemenu

**Comment by PoulpinSky** [comment] 2020-02-23 18:04
I've just try on a newest server and i've the same issue.

**Comment by PyvesB** [comment] 2020-02-23 18:11
You're trying to use `%aach_places_dirt%`, but you have no `Places` achievements based on a `dirt` sub-category. When you create a group of sub-categories to aggregate statistics, you have to use the grouped placeholder as well, for example `%aach_places_grass|dirt%`.

**Comment by PoulpinSky** [comment] 2020-02-23 20:36
Ok it work... Mb :/

But it seems not work with long place holder like
%aach_breaks_step|double_step|wood_double_step|wood_step|purpur_slab|purpur_double_slab|stone_slab2|double_stone_slab2%

**Comment by PyvesB** [comment] 2020-02-23 21:19
Hmmm, `PlayedTime` is probably in milliseconds since epoch. This should probably be converted to hours, like in the _/aach list_ GUI. Unless PlaceholderAPI can do those unit conversions automatically?

**Comment by PoulpinSky** [comment] 2020-02-23 21:31
I don't really know, but isn't a problem, i just wanted to know what is ^^
And can you check for the `%aach_enchantments%` placeholder ?

**Comment by PyvesB** [comment] 2020-02-23 21:39
> And can you check for the `%aach_enchantments%` placeholder ?

Could you please check the exact value that you specified as a placeholder? The value specified in [the Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/Placeholders) previously had a typo in it (an extra `e` in the middle 😄), you may have copied the bogus value.

**Comment by PoulpinSky** [comment] 2020-02-23 22:26
Exactly; it work perfect now, thank you !

**Comment by Bleache7500** [comment] 2020-02-25 20:38
Hi, i'm with poulpinsky. I just want to know if you can change the returns of %aach_playedtime% in hours ? Please

**Comment by PyvesB** [comment] 2020-02-25 21:38
> 
> 
> Hi, i'm with poulpinsky. I just want to know if you can change the returns of %aach_playedtime% in hours ? Please

Okay, can probably squeeze that in sometime this week.

**Comment by PyvesB** [comment] 2020-02-26 21:50
This should now be fixed. You can test it out with this version:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/4258338/AdvancedAchievements.zip)

Nothing much to add here, therefore closing. 😉

**Closed by PyvesB** 2020-02-26 21:50 UTC
Labels: general support
