### ISSUE TITLE
Idea - Json format Chat Notification

### ISSUE THREAD

**Issue by prozhong** [PyvesB/AdvancedAchievements#259] opened 2017-11-15 05:10 UTC
![9mlsby7nqwf pqq43kp_ex](https://user-images.githubusercontent.com/1495642/32819661-811e151a-ca05-11e7-87f5-53ce4e56cd3c.png)
(received the achievement: [Good Choice]
    hover info:  Welcome to our server !)

when hover it shows achievement's name, message, etc

**Comment by PyvesB** [comment] 2017-11-15 18:46
Hello prozhong,

That seems like a good idea, I'll give it a try and see how it looks! ;-)

Cheers,

Pyves

**Comment by PyvesB** [comment] 2017-11-15 22:47
Done! Here's a test version, would you like to give it a try? Make sure you enable the new `HoverableReceiverChatText` configuration parameter!

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1476627/AdvancedAchievements.zip)

**Comment by prozhong** [comment] 2017-11-16 07:42
It works like
![knj4 0g yool7_itt 80 b](https://user-images.githubusercontent.com/1495642/32879002-3da07402-cae3-11e7-8d5c-8d0117a562f0.jpg)

personally I think it would be better to not include all the things, especially rewards info..

Maybe just do it like in vanilla minecraft 
![04h1swn w p19_f7r9 1](https://user-images.githubusercontent.com/1495642/32879106-9ba09000-cae3-11e7-8199-9b7cb015d6b9.png)

so if I config like this

>     Message: '&6Welcome to our server !'
>     Name: connect_1
>     DisplayName: '&a[Good Choice]'
when hover it shows:
![image](https://user-images.githubusercontent.com/1495642/32879321-8371e730-cae4-11e7-9f8a-129c00c2abc5.png)

would be even better if I can config the middle line lore

**Comment by prozhong** [comment] 2017-11-16 07:46
Tested in 1.11.2

I don't use 1.12 so don't know how it looks like in new minecraft version

**Comment by PyvesB** [comment] 2017-11-17 19:02
I do think it should include all the information, including rewards. 😉 
- the hover as you show it conveys very little useful information. The first line is a duplicate of the chat message, the second line is a static text, only the third line adds information.
- it would be inconsistent and confusing for the player to have some of the additional information in the hover, and the rest in subsequent chat lines.

**Comment by prozhong** [comment] 2017-11-18 07:47
hmmmm...You are right
Player have a better user experience.

I think the hover info should show the info of this achievement, not rewards.
I mean the hover item is the achievement itself, everyone will be notify. The rewards info should only show to the player who finish the achievement, not all players
:)
Could you please let us toggle the format or customize it in config.yml ?

**Comment by PyvesB** [comment] 2017-11-18 10:09
I think there is some confusion here. I have changed the behaviour _only_ for the achievement receiver. Other players will only be able to see the achievement name as they did before (for instance via the action bar message), the rewards and precise description of the achievement will be kept secret as they should be.

**Comment by prozhong** [comment] 2017-11-18 17:24
I thought it would be a hover-Json-notify-others feature from the beginning, lol
In short, my idea was an new notify-others option which is more like vanilla achievement broadcast
not plain text or action bar

**Comment by prozhong** [comment] 2017-11-18 17:47
Say all the online players witness 1 player receiving his [Dragon Slayer Master] achievement
They hover it and see this
![image](https://user-images.githubusercontent.com/1495642/32983093-5b1793ce-ccca-11e7-9a72-adc1f68eeed7.png)
brief and like vanilla
That's all

**Comment by PyvesB** [comment] 2017-11-18 19:54
I had misunderstood your request, sorry. I don't think changing the notification shown to _other_ players is a good idea. Most administrators want to keep those messages hidden so that their players can have fun hunting the achievements without knowing the goals. Even if they choose to disclose all information via the plugin's configuration, it would just crowd the chat with hovers containing information they can easily get elsewhere, in _/aach list_ for instance. Also, most administrators write achievement messages in a "You [...]" form, which would not make sense and would be confusing when read by another player. Advanced Achievements does not aim at copying Vanilla features, instead it brings its own set of custom features with a different visual identity, I think is should stay that way rather than attempting to look like Mojang's not so popular Vanilla stuff. :wink:

**Comment by prozhong** [comment] 2017-11-19 05:24
Any chance give us a choice ? Even if you don't agree this feature, lol

**Comment by PyvesB** [comment] 2017-11-19 11:02
Why not simply fork the project and add this feature to your fork? The only file you would need to modify is _PlayerAdvancedAchievementListener.java_, it's decently commented and there are examples of how to build hovers inside. I also happy to help if you encounter any issue. :wink:

**Closed** 2017-11-19 15:26 UTC
Labels: enhancement
