### ISSUE TITLE
Lists with the Block Break achievements

### ISSUE THREAD

**Issue by JuhCohBee** [PyvesB/AdvancedAchievements#238] opened 2017-09-14 02:18 UTC
Can you add support for multiple blocks types with the Block Break Achievements? For example, if i wanted to make an achievement that counts all ore blocks broken, i would need to have a way to count multiple types of block breaks under one counter.

**Comment by PyvesB** [comment] 2017-09-14 06:40
Hello,

Closing as duplicate of #92. ;-)

Cheers,

Pyves

**Closed by PyvesB** 2017-09-14 06:40 UTC
Labels: duplicate
