### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by BabelSolea** [PyvesB/AdvancedAchievements#209] opened 2017-06-21 22:24 UTC
PlaceholderAPI is utility plugin her desigion to make possible use data from one plugin (aach here) in other plugins what manage some like: chat/items/gui/scorreboard/tablist/books/boss bar/title's/holograms/signs for show info/stats/ratings.

that easy to use and i saw few time what authors added that features less then 1-2 days after i (or other users) ask about it.

i want use
%aach_got_achivments% / %aach_max_achivments% in scoreboard - show like 19 / 150
%aach_top_weekly_<#1>% in chat annouces - show player's top#1 name

**and i see plugin LeaderHeads in 1.12 have error and cant show stats from your plugin - did ure change data mechanic?**

please look it and make your plugin more cool :D

would be nice to new feature - add PlaceholderAPI support
with placeholders like
%aach_got_achivments%
%aach_max_achivments%
%aach_top_<#1>% - 2-3-4 etc
+ weekly monthly lifetime

look how that working:
https://www.spigotmc.org/resources/placeholderapi.6245/

please add that awesome feature =)
for that need use PlaceholderAPI to create aach extension with aach placeholders =)))

to use that info in gui and scoreboard plugins.

**Comment by PyvesB** [comment] 2017-06-22 18:21
Hello,

Regarding PlaceholderAPI, this is a duplicate of #170.

Regarding LeaderHeads, that plugin has been broken for almost three months now (and almost 10 Advanced Achievements versions), and it seems that the author has progressively been dropping support even though the plugin is supposedly "premium". I nevertheless suggest you attempt chasing him up. ;-)

Cheers,

Pyves

**Closed by PyvesB** 2017-06-22 18:21 UTC
Labels: duplicate, wontfix/wontdo
