### ISSUE TITLE
Idea Mythicmobs

### ISSUE THREAD

**Issue by eot13** [PyvesB/AdvancedAchievements#318] opened 2018-02-17 08:01 UTC
Hello
Could you add the mythicmobs support: (killed mobs) please?

**Comment by PyvesB** [comment] 2018-02-17 10:48
Hello @eot13 !

Closing this as duplicate of #301. Also please refer to the [contributing guidelines](https://github.com/PyvesB/AdvancedAchievements/blob/master/CONTRIBUTING.md), which would have pointed you both to that issue and to the Wiki. 😉 

Cheers,

Pyves

**Closed by PyvesB** 2018-02-17 10:48 UTC
Labels: duplicate
