### ISSUE TITLE
Database Connection Failed

### ISSUE THREAD

**Issue by Sairiik** [PyvesB/AdvancedAchievements#771] opened 2020-07-04 06:39 UTC
:information_source: **Basic information**

* Advanced Achievements version: 6.1.2
* Minecraft version: 1.15.2
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: Yes
:question: **Help request**

:wrench: **Configuration**

````
Hello There , i am having an issues , i cannot connect my Database to the AACH Plugin , i tried several times already and it gives me this error code : 

> [08:34:47] [Server thread/INFO]: [AdvancedAchievements] Enabling AdvancedAchievements v6.1.2
> [08:34:47] [Server thread/INFO]: [AdvancedAchievements] Loading and backing up configuration files...
> [08:34:47] [Server thread/WARN]: [AdvancedAchievements] Overriding configuration: disabling PetMasterGive and PetMasterReceive categories.
> [08:34:47] [Server thread/WARN]: [AdvancedAchievements] Ensure you have placed Pet Master with a minimum version of 1.4 in your plugins folder or add PetMasterGive and PetMasterReceive to the DisabledCategories list in config.yml.
> [08:34:47] [Server thread/INFO]: [AdvancedAchievements] Loaded 58 achievements in 48 categories.
> [08:34:47] [Server thread/INFO]: [AdvancedAchievements] 3 disabled categories: [AdvancementsCompleted, PetMasterGive, PetMasterReceive]
> [08:34:47] [Server thread/INFO]: [AdvancedAchievements] Registering event listeners...
> [08:34:47] [Server thread/INFO]: [AdvancedAchievements] Initialising database...
> [08:34:56] [Server thread/ERROR]: [AdvancedAchievements] A non recoverable error was encountered while loading the plugin, disabling it:
com.hm.achievement.exception.PluginLoadError: Error while initialising database tables.
at com.hm.achievement.db.DatabaseUpdater.initialiseTables(DatabaseUpdater.java:121) ~[AdvancedAchievements%20(1).jar:?]
at com.hm.achievement.db.AbstractDatabaseManager.initialise(AbstractDatabaseManager.java:110) ~[AdvancedAchievements%20(1).jar:?]
at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:141) ~[AdvancedAchievements%20(1).jar:?]
at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:50) [AdvancedAchievements%20(1).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [server.jar:git-Spigot-800b93f-8160e29]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267) [server.jar:git-Spigot-800b93f-8160e29]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [server.jar:git-Spigot-800b93f-8160e29]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.sql.BatchUpdateException: No database selected
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1154) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1044) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:954) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.hm.achievement.db.DatabaseUpdater.initialiseTables(DatabaseUpdater.java:119) ~[?:?]
... 12 more
Caused by: java.sql.SQLException: No database selected
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1536) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1018) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:954) ~[server.jar:git-Spigot-800b93f-8160e29]
at com.hm.achievement.db.DatabaseUpdater.initialiseTables(DatabaseUpdater.java:119) ~[?:?]
... 12 more
> [08:34:56] [Server thread/INFO]: [AdvancedAchievements] Disabling AdvancedAchievements v6.1.2

I do not know what to do . 
````

**Comment by PyvesB** [comment] 2020-07-04 09:38
Hello @Sairiik,

As indicated by the error message, you need to specify the database you're using. For example in your _config.yml_ file:
````
DatabaseAddress: jdbc:mysql://localhost:3306/minecraft
````

In the above example, the selected database is `minecraft`. You should make sure that that database is created first, otherwise Advanced Achievements (or any other plugin for that matter) will not be able to conenct to it. 😉

**Comment by PyvesB** [comment] 2020-07-17 17:06
No news, good new, assuming the problem is solved. Closing the issue. :)

**Closed by PyvesB** 2020-07-17 17:06 UTC
Labels: general support
