### ISSUE TITLE
2 Bugs

### ISSUE THREAD

**Issue by AconTM** [PyvesB/AdvancedAchievements#323] opened 2018-02-24 21:35 UTC
1. When my Inventory is Full --> Item didnt give to me
2. When i die (Death Achivement) --> i didnt get Items..

**Comment by PyvesB** [comment] 2018-02-24 21:50
Hello @AconTM !

I will look into this. 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment] 2018-02-25 21:48
I am not able to reproduce either of the issues you have described. In both cases the items should fall on the ground and the player can them pick them up. Are you using the latest version of the plugin and a recent Spigot/Bukkit build? Are there any errors in the server's console?

**Comment by PyvesB** [comment] 2018-03-08 22:58
No news for some time, therefore closing. Feel free to reopen and provide additional information if the problem persists. 😉

**Closed by PyvesB** 2018-03-08 22:58 UTC
Labels: investigate
