### ISSUE TITLE
Could not pass event InventoryClickEvent to AdvancedAchievements v2.5.5

### ISSUE THREAD

**Issue by LLIaMMaH** [PyvesB/AdvancedAchievements#50] opened 2016-05-28 07:00 UTC
> [16:38:44 ERROR]: Could not pass event InventoryClickEvent to AdvancedAchievements v2.5.5
> org.bukkit.event.EventException
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
>         at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2015) [nh.class:?]
>         at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) [ix.class:?]
>         at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) [ix.class:?]
>         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
>         at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
> Caused by: java.lang.NullPointerException
>         at com.hm.achievement.listener.AchieveTradeAnvilBrewListener.onInventoryClick(AchieveTradeAnvilBrewListener.java:27) ~[?:?]
>         at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
>         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
>         ... 13 more
> [16:52:34 ERROR]: Could not pass event InventoryClickEvent to AdvancedAchievements v2.5.5
> org.bukkit.event.EventException
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
>         at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2015) [nh.class:?]
>         at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) [ix.class:?]
>         at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) [ix.class:?]
>         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
>         at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
> Caused by: java.lang.NullPointerException
>         at com.hm.achievement.listener.AchieveTradeAnvilBrewListener.onInventoryClick(AchieveTradeAnvilBrewListener.java:27) ~[?:?]
>         at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
>         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
>         ... 13 more

**Comment by PyvesB** [comment] 2016-05-28 09:32
Hello,

This issue is a duplicate of another one you opened two weeks ago; I had asked you for additional information on how to reproduce it, you just ignored me and started posting non related things on the issue, so I assumed it was solved.

If you continue on:
- spamming by duplicating identical issues,
- not providing any basic information or posting logs or links without any other explanations,
- going off context on your own issues,
- lacking basic good manners (remember, you are using free software, you should at least be polite when you ask and obtain help),
I will be forced to block you from the repository, as I am simply under the impression of wasting my time.

Furthermore, as stated on the Bukkit page, on the readme and on another issue, you must use Spigot (or plain Bukkit), and with a minimum version of 1.7.9; I cannot guarantee the support on other systems that have modified APIs or using older ones.

Cheers,

Pyves

**Closed** 2016-06-05 22:28 UTC
Labels: duplicate
