### ISSUE TITLE
Potion brewing glitch

### ISSUE THREAD

**Issue by JHarris12345** [PyvesB/AdvancedAchievements#740] opened 2020-05-21 09:47 UTC
:information_source: **Basic information**

* Advanced Achievements version: 6.1.0
* Minecraft version: 1.8 amd 1.15
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: Yes

:beetle: **Description**

If you take a potion out a brewing stand and put it back in the slot, it counts as another potion brewed. You can repeadetely just take it out the slot and put it back in to brew 100s of potions a minute
:page_facing_up: **Server logs**

````

````

:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment] 2020-05-23 10:36
>    [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: Yes

I strongly doubt it. Duplicate of #715, #559, #276,  #239, #125 and probably others.

**Closed by PyvesB** 2020-05-23 10:36 UTC
Labels: duplicate

**Comment by JHarris12345** [comment] 2020-05-23 10:37
Yeah and its been an issue since 2019, so you gonna fix it or shall I make a new issue on it next year?

**Comment by PyvesB** [comment] 2020-05-23 10:40
> 
> 
> Yeah and its been an issue since 2019, so you gonna fix it or shall I make a new issue on it next year?

Having an attitude will get you nowhere, especially on open-source projects.

**Comment by JHarris12345** [comment] 2020-05-23 11:50
Just a bit stupid its been an issue for a year now
