### ISSUE TITLE
Multiple types tracking

### ISSUE THREAD

**Issue by Platinteufel** [PyvesB/AdvancedAchievements#403] opened 2018-07-28 04:00 UTC
_Note that when you create a new group of types with `|`, progress will start at 0 regardless of existing player statistics for any of the types considered individually. Also, if ever you add/remove a type from the group, progress for this sub-category group will start back at 0 as well._

If I don't want to lose any statistics I obviously need to manipulate my database. Since you have way more knowledge than me: There should be an easy sql command to change all **oak_wood** entries to **oak_log|birch_log|spruce_log|dark_oak_log|jungle_log**. Am I right that it was something like this?

`UPDATE table_name
SET some_column = some_value
WHERE some_column = some_value;
`

Can I do anything wrong if I try it this way? Or is there even a simple aach command for performing database updates for those cases? Since there's also the new `/aach upgrade13` command it seems to be possible to perform database manipulations without a lot of effort?

Cheers ;-)

**Comment by PyvesB** [comment] 2018-07-28 07:48
Hello @Platinteufel ,

Actually I believe that there is no SQL query to do so, as `oak_wood` corresponds to a primary key in the database tables, and such values can't easily be changed.

The _/aach upgrade13_ does do similar manipulations, but in more extreme way: it creates a duplicate of the database table, copies over all the values and changes them, drops the old table and renames the new one.

No similar process has been added in the pull request adding support for grouping multiple sub-categories (#341). It would probably have to be another manual command performing table copies and transformations, and it would have to cope with quite a few edge cases in addition to the simple `oak_wood` -> `oak_log|birch_log|spruce_log|dark_oak_log|jungle_log` case you highlighted:
* it would need to sum statistics if we're grouping on several items that already existed.
* if one of the existing groups already contains several items of a new group, we don't want to sum in this case as we would duplicate the counts.
* it would need to be clever enough to know when it has to keep both the ungrouped and the grouped items, if the user has left both in his configuration.
* what would it do if the user deletes an item from the group, should the entire group be reset or kept as is, even though all statistics might have been acquired thanks to the now deleted item?

Overall it seems complex to design, error prone, and I don't think it's worth the effort.

In your case, you could manually hack around the [code of the upgrade13 command](https://github.com/PyvesB/AdvancedAchievements/blob/d97b65f3412346547bfed970744af8ffa7658d5f/advanced-achievements-plugin/src/main/java/com/hm/achievement/db/DatabaseUpdater.java#L351), and instead of calling `convertToNewMaterialKey` simply replace you old `oak_wood` key by `oak_log|birch_log|spruce_log|dark_oak_log|jungle_log`. 😉 

Cheers,

Pyves

**Comment by Platinteufel** [comment] 2018-07-28 08:54
Thank you for your answer! ;)
I didn't even think about any "smart" command, I had in mind a simple command for key manipulations, like /aach convert <oldKey> <newKey>
and so for my example /aach convert oak_log oak_log|birch_log|spruce_log|dark_oak_log|jungle_log
But I will try your suggestion, thanks. :)

To be honest, I don't know much about databases. As I saw this feature tomorrow I thought it will generate seperate entries for oak_log, birch_log, spruce_log, ... and count them together, so that the number of the whole subcategory is the sum of it's parts. If you remove a part, for example birch_log, it just won't be added anymore. 
But I'm not even sure if it's possible this way. :D

**Closed** 2018-08-17 18:59 UTC
Labels: question/general support
