### ISSUE TITLE
Achievement tracking problems

### ISSUE THREAD

**Issue by evanmcclan** [PyvesB/AdvancedAchievements#348] opened 2018-05-01 19:53 UTC
Plugin version: 5.7.2
Minecraft verison: CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Problem**: 
For all of my achievements (especially in the custom categories). the plugin doesn't track if the player already has the achievement before giving it to them. Because of this it allows the player to keep receiving the same achievement over again through the give command or through console. Please fix this issue because achievements should only be given one time and the reward only one time (unless the admin removes the achievement from the player in which case they can get it back again).

Another problem is in the **aach list** command GUI. All the items in the gui can be removed, all the blocks for each achievement can be taken out of the GUI and put into a players inventory when they shouldn't be.

for all of the errors ive mentioned, the plugin generates no error messages in the console at all.

**Comment by PyvesB** [comment] 2018-05-01 21:54
Hello @evanmcclan ,

I suggest reading the plugin's configuration file as well as the Wiki. 😉 

Cheers,

Pyves

**Comment by evanmcclan** [comment] 2018-05-09 20:47
@PyvesB I read the configuration and the Lang.YML file. It appears that there is no errors in the yml and there is no UTF-encoding issues. Ive tried every method i could think of to figure out why items in **aach list** are still removabled from the GUI. Any suggestions?

**Comment by PyvesB** [comment] 2018-05-09 21:39
Could you please share your _lang.yml_ file so I can take a look?

**Comment by evanmcclan** [comment] 2018-05-10 02:51
@PyvesB https://pastebin.com/bW4X4fkT (Sorry for the late response)

**Comment by PyvesB** [comment] 2018-05-10 17:26
I am not able to reproduce this issue with your configuration, I am suspecting some sort of conflict with another plugin. Do things work fine when Advanced Achievements is the only plugin running on the server?

**Comment by evanmcclan** [comment] 2018-05-10 19:12
@PyvesB When AdvancedAchievements is running as the only plugin on the server it does work. 
What types of plugins would most likely conflict?
Economy | GUI | CustomCommand Makers | Protocol Plugins ....?

**Comment by PyvesB** [comment] 2018-05-10 19:33
Most likely the GUI or Protocol plugins, but as I don't know most of these plugins, it's hard to tell. I suggest trying to re-enable your plugins by batches of 5-10, and see when Advanced Achievements stops working properly. You can then search the specific plugin within that batch. Once we've spotted the culprit, we can carry on from there. ^^

**Comment by evanmcclan** [comment] 2018-05-10 22:32
Ok I think ive found the problem. When I Re-add EssentialsX The Achievements list gui breaks

**Comment by evanmcclan** [comment] 2018-05-19 17:02
@PyvesB **Hi sorry it took me so long to respond, my email notifications stopped working. Attatched below is my config.
https://pastebin.com/8a4uxfdg

**Comment by PyvesB** [comment] 2018-05-20 09:57
Unfortunately I'm still not able to reproduce the issue. Let's try a different strategy here. I have attached a test version that contains some additional log lines. Could you please try to get an item out of the GUI and show me the messages from Advanced Achievements that appear in the console's output?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2020214/AdvancedAchievements.zip)

**Comment by evanmcclan** [comment] 2018-05-23 21:22
@PyvesB The Jar you gave me works, the items cant be clicked out of the GUI and the console outputs this; `23.05 16:20:34 [Server] INFO Evan_McClan issued server command: /aach list
23.05 16:20:36 [Server] INFO Inventory name is "My Achievements"
23.05 16:20:36 [Server] INFO Event cancelled : true`
Is there a way to remove the `1` it puts after the GUI name or is that a page number?

**Comment by PyvesB** [comment] 2018-05-23 22:00
Wait a minute, I haven't actually made any actual changes apart from the logging, the _jar_ should be functionally equivalent to version 5.7.4 of the plugin. Does it break again when you switch back to the latest official version of the plugin?

**Comment by evanmcclan** [comment] 2018-05-23 23:13
the latest version now no longer lets me remove the items from the GUI, however, the gui title still adds the number 1 when i open a category

**Comment by PyvesB** [comment] 2018-05-24 06:41
You must have changed something on your side to fix the issue. I noticed that you had modified the title of the GUI, the single quote your were using previously is in fact a special character in YAML, this might have messed around with your configuration.

The number is the page number.

**Comment by PyvesB** [comment] 2018-05-25 17:55
Oops accidentally deleted my comment, rewriting it.

1 -> page number.

I'm assuming you changed something else on your side. I noticed you changed `list-gui-title`, which actually previously contained an apostrophe. Thismay have cause problems as it's a special character in YAML.

**Comment by PyvesB** [comment] 2018-05-31 18:49
Closing this issue. Please upgrade to version 5.8.0 of the plugin once it's released, there are some improvements regarding things we discussed here. 😉

**Closed by PyvesB** 2018-05-31 18:49 UTC
Labels: investigate
