### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by andris155** [PyvesB/AdvancedAchievements#386] opened 2018-07-10 12:15 UTC
```
[14:10:42] [Server thread/ERROR]: Could not pass event InventoryClickEvent to AdvancedAchievements v5.8.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1468]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1981) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1468]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1468]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by andris155** [comment] 2018-07-10 12:21
Config
https://pastebin.com/TgGz3isL

**Comment by supertassu** [comment] 2018-07-10 13:57
You've cut out the important part of the error. We need the log lines after `Caused by: java.lang.ArrayIndexOutOfBoundsException`. 

Possibly related to #377

**Comment by andris155** [comment] 2018-07-10 14:33
```
[14:10:39] [Server thread/ERROR]: Could not pass event InventoryClickEvent to AdvancedAchievements v5.8.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1468]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1981) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1468]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1468]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -50
	at java.util.ArrayList.elementData(ArrayList.java:422) ~[?:1.8.0_171]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_171]
	at com.hm.achievement.gui.CategoryGUI.displayPage(CategoryGUI.java:201) ~[AdvancedAchievements%20(2).jar:?]
	at com.hm.achievement.gui.CategoryGUI.displayCategoryGUI(CategoryGUI.java:158) ~[AdvancedAchievements%20(2).jar:?]
	at com.hm.achievement.listener.ListGUIListener.onInventoryClick(ListGUIListener.java:64) ~[AdvancedAchievements%20(2).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor469.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1468]
	... 16 more
```

**Comment by supertassu** [comment] 2018-07-10 14:51
Most likely duplicate of #336; please see https://github.com/PyvesB/AdvancedAchievements/issues/336#issuecomment-377493836 for a solution.

Thought 1935063754dd4a4ff124f30ae8e973fd0137cd67 fixed this. Weird.

**Comment by Rsl1122** [comment] 2018-07-14 17:47
Suggested comment does not solve the issue - the config sent by @andris155 contains Commands: {} on line 707

----

ArrayIndexOutOfBoundsException: -50 suggests that an attempt to get page with pageIndex of -1 was made

CommandsGUI.java
```
private void displayPage(...) {
	int pageIndex = getPageIndex(requestedIndex, achievementPaths.size());
	int pageStart = MAX_PER_PAGE * pageIndex; // MAX_PER_PAGE is 50
	...
	for (int index = pageStart; index < pageEnd; ++index) {
		String path = achievementPaths.get(index); // Exception
```

**Comment by supertassu** [comment] 2018-07-14 18:04
@rsl122
Commands is not on DisabledCategories:

```
DisabledCategories:
- PetMasterGive
- PetMasterReceive
- DistanceLlama
- Custom
```

**Comment by PyvesB** [comment] 2018-07-26 21:06
Assuming everything is now fixed, closing the issue. 😉

**Closed by PyvesB** 2018-07-26 21:06 UTC
Labels: question/general support
