### ISSUE TITLE
PlayerBucketFillEvent event exception due to NoClassDefFoundError

### ISSUE THREAD

**Issue by Alperenn** [PyvesB/AdvancedAchievements#391] opened 2018-07-14 17:02 UTC
`[20:01:51 ERROR]: Could not pass event PlayerBucketFillEvent to AdvancedAchievements v5.8.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:179) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerBucketFillEvent(CraftEventFactory.java:156) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ItemBucket.a(ItemBucket.java:46) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.ItemStack.a(ItemStack.java:236) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.useItem(PlayerInteractManager.java:371) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:734) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [Spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: com/hm/achievement/listener/statistics/MilksLavaWaterBucketsListener$1
        at com.hm.achievement.listener.statistics.MilksLavaWaterBucketsListener.getCategory(MilksLavaWaterBucketsListener.java:75) ~[?:?]
        at com.hm.achievement.listener.statistics.MilksLavaWaterBucketsListener.onPlayerBucketFill(MilksLavaWaterBucketsListener.java:60) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor443.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
        ... 21 more
`

**Comment by supertassu** [comment] 2018-07-14 17:14
Duplicate of #377

**Comment by PyvesB** [comment] 2018-07-14 20:53
@supertassu I think this is a different issue as the cause of the exception is `NoClassDefFoundError`.

@Alperenn did you happen to swap the plugin file whilst the server was running? Is this issue happing on a regular basis?

**Comment by Alperenn** [comment] 2018-07-14 20:59
i had solve problem

**Comment by Alperenn** [comment] 2018-07-14 21:00
I solved the problem

**Comment by PyvesB** [comment] 2018-07-14 21:06
Okay, awesome, closing this issue. 😉

**Closed by PyvesB** 2018-07-14 21:06 UTC
Labels: question/general support
