### ISSUE TITLE
Error on /aach generate

### ISSUE THREAD

**Issue by iAzk** [PyvesB/AdvancedAchievements#281] opened 2017-12-18 00:47 UTC
Version: Spigot.1.12
Last version of plugin: Yes

Error: https://hastebin.com/faqojasotu.bash

**Comment by PyvesB** [comment] 2017-12-18 07:47
Hello iAzk,

Please try restarting your server. If it doesn't help fry manually deleting the advancements on your server. Unfortunately the advancements system is really unstable and unreliable, and Spigot still doesn't provide a proper API over 6 months after the release of Minecraft 1.12. :/

Cheers, 

Pyves

**Comment by Sprungente** [comment] 2017-12-24 16:27
i'm sure it will happen after config change. Same as me #275 

everytime the custon achievement is the problem.

@PyvesB Maybe with a Jiraticket or mailing md_5 about advancement could bringing more help for the unstable problem

**Comment by PyvesB** [comment] 2017-12-26 16:15
@Sprungente : After a very quick search, several issues that seem to be closely linked to this one have already been reported, but unfortunately closed:
- [SPIGOT-3512](https://hub.spigotmc.org/jira/browse/SPIGOT-3512)
- [SPIGOT-3627](https://hub.spigotmc.org/jira/browse/SPIGOT-3627)

Last time I opened a JIRA ticket, it was closed as well within less than an hour with no possible discussion. The reasoning was weak and completely contradictory compared to another very similar regression that had been reverted a few days before. Unfortunately, Spigot's JIRA is not welcoming, the lead developers lack manners and the board's settings are ridiculously restrictive. Another developer I know quite well has had similar negative experiences. I do not intend to attempt opening new bug reports.

As far as the advancements API is concerned, I believe @Chazmondo had at some point planned to open a pull request, I don't know whether there has been progress.

Back to _/aach generate_, could you please send me your _config.yml_? I can try playing around with it on my side and see whether I have missed something in Advanced Achievements' code. :wink:

**Comment by Sprungente** [comment] 2017-12-27 23:09
too bad that spigot isn't open for it. Try to write md5 an email ( plugins@md-5.net ) and talking with him about this issue. When he wanna say, make a bug report so you can say it in Jira or say md5 about the jirasituation.  It looks that we have to fight for a bugfix 🤣 

To the issue

Download here:

https://workupload.com/file/bxsQ2JG 

Try out: Change a value in a Achievement
- Change storagetype sqlite to mysql

**Comment by PyvesB** [comment] 2017-12-28 09:35
Unfortunately I'm not able to reproduce your issue. Here's how I have been proceeding:
- run _/aach generate_.
- modify an existing achievement as you indicated.
- run _/aach reload_ to pick up the new configuration.
- run _/aach generate_ again.

I've tried this five times in a row with your configuration, and have attempted to modify different achievements in different ways. The command was systematically successful.

I'm running Advanced Achievements version 5.5 with the following Spigot build:
`CraftBukkit version git-Spigot-00128b5-6cb752e (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

**Comment by PyvesB** [comment] 2018-01-06 22:06
@iAzk @Sprungente Any news?

**Comment by Sprungente** [comment] 2018-01-08 02:12
Oh i didn't see that you need datas :O I'm sorry 

Here: https://transferxl.com/08vN0ShxfDJbrN

Could bungeecord be trigger this issue?

**Comment by PyvesB** [comment] 2018-01-09 19:35
Still not able to reproduce with your server's configuration. I doubt BungeeCord would have anything to do with advancement issues. Have you got any other plugins that interact with advancements or that alter how the server works/restarts?

**Comment by Sprungente** [comment] 2018-01-11 03:07
no :/ 
But i have maybe a groundbreaking discovery:

AACH Advancement exist after is generated but AACH Advancement don't save in the player Advancement Jsonfile, only normal minecraftadvancement. After restart AACH Advancement don't exist but stay in advancements/advancedachievements. When i type now /aach generate the error will occour.

But i don't know why it is on your testserver without problems. Is my server cursed?

I have no idea what's reason is for my problem :/

**Comment by Sprungente** [comment] 2018-01-13 01:33
Maybe Mypet create this problem

After i hit a pet, the other has removed it and then i got all Achievements, that i had reached in AACH.

@iAzk do you have the plugin too?

**Comment by PyvesB** [comment] 2018-01-14 17:39
Does _MyPet_ actually have anything to do with advancements?

**Comment by PyvesB** [comment] 2018-01-25 21:47
I'll keep this issues opened for now, we still need to find a reliable way to reproduce these errors to make progress. Any help or contributions are welcome. 😉

**Comment by PyvesB** [comment] 2018-08-07 21:31
I've done some work around advancements in #405. Feel free to give this new version a try, it _might_ help:
[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2268127/AdvancedAchievements.zip)

**Comment by PyvesB** [comment] 2018-08-17 18:57
It has been well over 6 months since anyone has reported any similar errors with the _/aach generate_ command. A lot has changed in Advanced Achievements and in Bukkit/Spigot since then, so I'm assuming this is no longer a problem. Please upgrade to the latest version of your server software and of the plugin if you are still facing any issues.

**Closed by PyvesB** 2018-08-17 18:57 UTC
Labels: investigate

**Comment by Sprungente** [comment] 2018-10-05 01:04
Oh you closed it. I'm so late xD. 

It fixed with the time. This issue don't exist anymore. I don't know what you have done but it works
